#!/bin/bash

#requires graphviz

if [[ ($# -ne 1) && ($# -ne 2) ]] #expects 1-2 arguments: input and output (can generated by default)
then
	echo "usage: $0 <input-dot-file> [output-png-file]"
	exit 65 # bad arguments
fi

INFILE=$1

if [[ $# -eq 1 ]]
then
	OUTFILE=$(echo $INFILE | rev | cut -d"." -f2- | rev)".png"
else
	OUTFILE=$2
fi

dot -Tpng -o"$OUTFILE" $INFILE
